Added blob public access and CORS rule options
hmcts/cnp-module-storage-account pull request #23
Opened 2022-01-14 13:00 UTC by adamtodd0

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-1011

### Change description ###
Added options for blob public access and CORS rules. 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-01-14 13:24 UTC, chris-pateman requested changes

2022-01-14 13:24 UTC, chris-pateman commented on variables.tf
> +variable "cors" {
Can you add some validation for the 'allowed_methods' please.
https://www.terraform.io/language/values/variables#custom-validation-rules

2022-01-14 13:24 UTC, chris-pateman commented on main.tf
> +	  cors_rule {
Can this block be dynamic depending if the 'allowed_origins' has any inputs please

2022-01-17 15:51 UTC, chris-pateman requested changes

2022-01-17 15:51 UTC, chris-pateman commented on main.tf
> +			allowed_headers = var.cors_rules.allowed_headers
to access the value from the loop for_each you will need to access the properties like `each,value.allowed_headers` 
https://www.terraform.io/language/meta-arguments/for_each

2022-01-18 14:58 UTC, chris-pateman approved these changes
LGTM

2022-01-18 15:27 UTC, timja approved these changes

2022-01-18 15:53 UTC, merged